LCompType = { }
LCompType.Model = 101 --模型
LCompType.CharacterController = 102 -- cc
LCompType.Speed = 103 --速度
LCompType.Rotation = 104 --方向
LCompType.Gravity = 105 --重力
LCompType.Position = 106 --位置
LCompType.Animator = 107 --anim
LCompType.BillBoard = 200 --姓名版