Rigidbody = typeof(CS.UnityEngine.Rigidbody)
CharacterController = typeof(CS.UnityEngine.Rigidbody)
CSImage = typeof(CS.UnityEngine.UI.Image)
CSButton = typeof(CS.UnityEngine.UI.Button)
CSText = typeof(CS.UnityEngine.UI.Text)